name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          rm -f package-lock.json
          npm install

      - name: Build
        run: npm run build

      - name: Deploy via SSH sshpass
        env:
          SSH_PASS: ${{ secrets.SSH_PASSWORD }}
        run: |
          sudo apt-get install -y sshpass rsync
          sshpass -p "$SSH_PASS" rsync -avzr --delete -e "ssh -p 65002 -o StrictHostKeyChecking=no" dist/ u212110799@46.202.186.67:/home/u212110799/public_html/