name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          rm -f package-lock.json
          npm install

      - name: Build
        run: npm run build

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 46.202.186.67
          port: 65002
          username: u212110799
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            rm -rf ~/public_html/*

      - name: Copy files via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 46.202.186.67
          port: 65002
          username: u212110799
          password: ${{ secrets.SSH_PASSWORD }}
          source: "dist/*"
          target: "~/public_html/"
          strip_components: 1